build: off

install:
  - git submodule update --init
  - choco install openjdk --version 11.0.2.01 --params "installdir=C:\\jdk11"
  - SET JAVA_HOME=C:\jdk11
  - SET PATH=C:\jdk11\bin;%PATH%

cache:
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - C:\jdk11 -> appveyor.yml
  - '%USERPROFILE%\.gradle -> appveyor.yml'

test_script:
  - cd pretixscan
  - gradlew --no-daemon -version
  - gradlew --no-daemon --stacktrace clean check test build
  - mkdir dist
  - '"C:\Program Files (x86)\NSIS\makensis.exe" windows.nsi'

artifacts:
  - path: pretixscan\dist\pretixscan.exe
    name: Installer

