build: off

install:
  - git submodule update --init
  - cinst jdk10 -version 10.0.1.10 -params 'installdir=C:\\jdk10'
  - SET JAVA_HOME=C:\jdk10
  - SET PATH=C:\jdk10\bin;%PATH%
  - ps: .\pretixdesk\winci\downloadjre.ps1
  - 7z e pretixdesk\winci\jre-10.0.1_windows-x64_bin.tar.gz
  - 7z x jre-10.0.1_windows-x64_bin.tar
  - move jre-10.0.1 jre
  - move jre pretixdesk\

cache:
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - C:\jdk10 -> appveyor.yml
  - '%USERPROFILE%\.gradle -> appveyor.yml'
  - pretixdesk\winci\jre-10.0.1_windows-x64_bin.tar.gz

test_script:
  - cd pretixdesk
  - gradlew --no-daemon -version
  - gradlew --no-daemon --stacktrace clean check test build fatJar createExe
  - mkdir dist
  - '"C:\Program Files (x86)\NSIS\makensis.exe" windows.nsi'

artifacts:
  - path: pretixdesk\dist\pretixdesk.exe
    name: Installer

