build: off

install:
  - git submodule update --init
  - choco install openjdk --version 13.0.101
  - SET JAVA_HOME=C:\Program Files\OpenJDK\jdk-13.0.1
  - SET PATH=C:\Program Files\OpenJDK\jdk-13.0.1\bin;%PATH%
  - curl -o jdk.packager-windows.zip http://download2.gluonhq.com/jpackager/13/jdk.packager-windows.zip
  - 7z e jdk.packager-windows.zip
  - curl -o jmods.zip https://download2.gluonhq.com/openjfx/13.0.1/openjfx-13.0.1_windows-x64_bin-jmods.zip
  - 7z x jmods.zip
  - mv jpackager.exe "%JAVA_HOME%\bin"
  - mv jdk.packager.jar "%JAVA_HOME%\jmods"

cache:
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - '%USERPROFILE%\.gradle -> appveyor.yml'

test_script:
  - cd pretixscan
  - gradlew --no-daemon -version
  - gradlew --no-daemon --stacktrace clean createBundle -PjavafxJmodsPath=../../javafx-jmods-13.0.1/
  - mkdir dist
  - '"C:\Program Files (x86)\NSIS\makensis.exe" packaging\build\resources\main\windows.nsi'

artifacts:
  - path: pretixscan\dist\pretixSCAN.exe
    name: Installer

