build: off

install:
  - git submodule update --init
  - choco install openjdk --version 11.0.2.01
  - SET JAVA_HOME=C:\Program Files\OpenJDK\jdk-11.0.2
  - SET PATH=C:\Program Files\OpenJDK\jdk-11.0.2\bin;%PATH%
  - curl -o jdk.packager-windows.zip http://download2.gluonhq.com/jpackager/11/jdk.packager-windows.zip
  - 7z e jdk.packager-windows.zip
  - curl -o jmods.zip https://download2.gluonhq.com/openjfx/11.0.2/openjfx-11.0.2_windows-x64_bin-jmods.zip
  - 7z x jmods.zip
  - mv jpackager.exe "%JAVA_HOME%\bin"
  - mv jdk.packager.jar "%JAVA_HOME%\jmods"
  - curl -o mvn.zip https://www-us.apache.org/dist/maven/maven-3/3.6.2/binaries/apache-maven-3.6.2-bin.zip
  - 7z x mvn.zip
  - cd pretixscan\tornadofx-repo
  - ..\..\apache-maven-3.6.2\bin\mvn package
  - cd ..\..

cache:
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - '%USERPROFILE%\.gradle -> appveyor.yml'

test_script:
  - cd pretixscan
  - gradlew --no-daemon -version
  - gradlew --no-daemon --stacktrace clean createBundle -PjavafxJmodsPath=../../javafx-jmods-11.0.2/
  - mkdir dist
  - '"C:\Program Files (x86)\NSIS\makensis.exe" packaging\build\resources\main\windows.nsi'

artifacts:
  - path: pretixscan\dist\pretixSCAN.exe
    name: Installer

