package:
    before_script:
        - wget https://download2.gluonhq.com/openjfx/11.0.2/openjfx-11.0.2_linux-x64_bin-jmods.zip
        - wget https://download2.gluonhq.com/jpackager/11/jdk.packager-linux.zip
        - unzip jdk.packager-linux.zip
    script:
        - cd pretixscan
        - ./gradlew clean createBundle -PjavafxJmodsPath=../javafx-jmods-11.0.2/ -PjavaPackagerPath=../
    tags:
        - java
    artifacts:
        paths:
            - pretixscan/packaging/build/bundle/
